name: Daily Spotify Data Collection

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  collect-spotify-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install spotipy boto3 python-dotenv schedule requests structlog tenacity pydantic-settings jsonlines pandas pyarrow
        
    - name: Create .env file
      run: |
        cat > .env << EOF
        SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REDIRECT_URI=http://127.0.0.1:8888/callback
        SPOTIFY_REFRESH_TOKEN=${{ secrets.SPOTIFY_REFRESH_TOKEN }}
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION=us-west-2
        S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
        FETCH_INTERVAL_MINUTES=30
        BATCH_SIZE=50
        MAX_RETRIES=3
        SNOWFLAKE_STAGE_PREFIX=spotify_listening_history/
        DATE_PARTITION_FORMAT=%Y/%m/%d
        EOF
        
    - name: Run Spotify data collection
      run: |
        python main.py --enable-artist-genre-processing run-once
        
    - name: Show pipeline stats
      run: |
        python main.py --enable-artist-genre-processing stats